
services:
  shop:
    build: .
    image: shop-anniversary:latest
    container_name: shop-anniversary-web
    restart: always
    ports:
      - "3080:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@localhost:5432/shop_anniversary?schema=public
      - NODE_ENV=production
      - INTERNAL=false
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=user@example.com
      - SMTP_PASS=password
      - SMTP_SECURE=false
      - SMTP_FROM='"Shop Anniversary" <noreply@eagletrt.it>'
