packages: []
allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  '@prisma/engines': true
  esbuild: true
  prisma: true
supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
